version: '2'
services:
  jinniukuaigouapplicationvue-app:
    image: jinniukuaigouapplicationvue
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://jinniukuaigouapplicationvue-mysql:3306/jinniukuaigouapplicationvue?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
      - SPRING_DATA_JEST_URI=http://jinniukuaigouapplicationvue-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://jinniukuaigouapplicationvue-elasticsearch:9200
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
    ports:
      - 8080:8080
  jinniukuaigouapplicationvue-mysql:
    extends:
      file: mysql.yml
      service: jinniukuaigouapplicationvue-mysql
  jinniukuaigouapplicationvue-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: jinniukuaigouapplicationvue-elasticsearch
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
